/*
 * This source file was generated by the Gradle 'init' task
 */
package gradleproject;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;

public class ToDoApp extends JFrame {

    private static final String DATA_FILE = "tasks.dat";

    private TaskManager manager;

    private DefaultListModel<Task> listModel;
    private JList<Task> taskList;
    private JTextField txtDescription;
    private JButton btnAdd, btnUpdate, btnComplete, btnDelete, btnShowCompleted, btnShowAll, btnSave;

    public ToDoApp() {
        super("ToDo List");

        manager = new TaskManager();
        manager.loadFromFile(DATA_FILE);   // load saved tasks

        initComponents();
        loadAllTasksIntoList();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(600, 400);
        setLocationRelativeTo(null);       // center window
    }

    private void initComponents() {
        listModel = new DefaultListModel<>();
        taskList = new JList<>(listModel);
        taskList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        txtDescription = new JTextField();

        btnAdd = new JButton("Add");
        btnUpdate = new JButton("Update");
        btnComplete = new JButton("Complete");
        btnDelete = new JButton("Delete");
        btnShowCompleted = new JButton("Show Completed");
        btnShowAll = new JButton("Show All");
        btnSave = new JButton("Save");

        setLayout(new BorderLayout());

        add(new JScrollPane(taskList), BorderLayout.CENTER);

        JPanel bottomPanel = new JPanel(new BorderLayout());
        bottomPanel.add(txtDescription, BorderLayout.CENTER);

        JPanel buttonPanel = new JPanel(new GridLayout(2, 4, 5, 5));
        buttonPanel.add(btnAdd);
        buttonPanel.add(btnUpdate);
        buttonPanel.add(btnComplete);
        buttonPanel.add(btnDelete);
        buttonPanel.add(btnShowCompleted);
        buttonPanel.add(btnShowAll);
        buttonPanel.add(btnSave);

        bottomPanel.add(buttonPanel, BorderLayout.SOUTH);
        add(bottomPanel, BorderLayout.SOUTH);

        // Listeners
        btnAdd.addActionListener(this::onAdd);
        btnUpdate.addActionListener(this::onUpdate);
        btnComplete.addActionListener(this::onComplete);
        btnDelete.addActionListener(this::onDelete);
        btnShowCompleted.addActionListener(this::onShowCompleted);
        btnShowAll.addActionListener(this::onShowAll);
        btnSave.addActionListener(this::onSave);

        taskList.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                Task selected = taskList.getSelectedValue();
                if (selected != null) {
                    txtDescription.setText(selected.getDescription());
                }
            }
        });
    }

    private void loadAllTasksIntoList() {
        listModel.clear();
        List<Task> all = manager.getAllTasks();
        for (Task t : all) {
            listModel.addElement(t);
        }
    }

    private void loadCompletedTasksIntoList() {
        listModel.clear();
        List<Task> done = manager.getCompletedTasks();
        for (Task t : done) {
            listModel.addElement(t);
        }
    }

    private void onAdd(ActionEvent e) {
        String desc = txtDescription.getText().trim();
        if (desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Description cannot be empty");
            return;
        }
        Task t = manager.createTask(desc);
        listModel.addElement(t);
        txtDescription.setText("");
    }

    private void onUpdate(ActionEvent e) {
        Task selected = taskList.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Select a task to update");
            return;
        }
        String newDesc = txtDescription.getText().trim();
        if (newDesc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Description cannot be empty");
            return;
        }
        if (manager.updateTask(selected.getId(), newDesc)) {
            int idx = taskList.getSelectedIndex();
            listModel.set(idx, selected);  // same object, updated text in toString
        }
    }

    private void onComplete(ActionEvent e) {
        Task selected = taskList.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Select a task to complete");
            return;
        }
        if (manager.completeTask(selected.getId())) {
            int idx = taskList.getSelectedIndex();
            listModel.set(idx, selected);
        }
    }

    private void onDelete(ActionEvent e) {
        Task selected = taskList.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Select a task to delete");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
                this, "Delete selected task?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (manager.deleteTask(selected.getId())) {
                listModel.removeElement(selected);
                txtDescription.setText("");
            }
        }
    }

    private void onShowCompleted(ActionEvent e) {
        loadCompletedTasksIntoList();
    }

    private void onShowAll(ActionEvent e) {
        loadAllTasksIntoList();
    }

    private void onSave(ActionEvent e) {
        manager.saveToFile(DATA_FILE);
        JOptionPane.showMessageDialog(this, "Tasks saved.");
    }

    // MAIN: start Swing GUI instead of console menu
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {      // run GUI on EDT[web:103][web:110]
            new ToDoApp().setVisible(true);
        });
    }
}
